export const SAVE_CREDIT_CARD_DETAILS = "SAVE_CREDIT_CARD_DETAILS";
export const SAVE_CVV = "SAVE_CVV";
export const SET_SELECTED_CARD = "SET_SELECTED_CARD";
export const SET_AGREE_TERMS = "SET_AGREE_TERMS";
